### PR TITLE
fix(emscripten): ensure EMSDK setup completes before WASM compilation

### LINKED ISSUE #53: imgui: not found `assert.h` on wasm32 target
```bash
In file included from ./src/imgui/dcimgui.c:5:
/home/runner/.cache/zig/p/1220c640ad23d8800437166865e54f172c612fcfe6e000149a2b2af631c37b605f50/src/cimgui.h:93:10: fatal error: 'assert.h' file not found
   93 | #include <assert.h>
      |          ^~~~~~~~~~
1 error generated.
./src/imgui/package.d(15,15): Error: cannot find input file `./src/imgui/dcimgui.c`
public import imgui.dcimgui;
              ^
```
source: https://github.com/floooh/dcimgui/blob/9356c08eb4d1d320e79e418a36d59a427627634a/src/cimgui.h#L92-L95

### PR DESCRIPTION
**Pull request by kassane**
closes #53

based on: https://github.com/floooh/sokol-zig-imgui-sample/blob/main/build.zig

### CODE REVIEW

File: build.zig [hunk 1]
```diff
@@ -1155,31 +1195,42 @@ const libImGuiOptions = struct {
...
     const libimgui = b.addStaticLibrary(.{
         .name = "imgui",
         .target = options.target,
         .optimize = options.optimize,
     });
+
     libimgui.root_module.sanitize_c = options.use_ubsan;
     libimgui.root_module.sanitize_thread = options.use_tsan;
 
+    if (options.target.result.isWasm()) {
```
Comment (kassane) [inline build.zig:1216]: Here, I've tried avoiding redundancies in calling emsdk using the below workaround. However, I still get the same error!
```zig
for(options.lib_sokol.root_module.include_dirs.items) |dir| {
        try libimgui.root_module.include_dirs.append(b.allocator,dir);
    }
```

File: build.zig [hunk 2]
```diff
@@ -243,12 +260,35 @@ pub fn build(b: *Build) !void {
...
         .with_sokol_imgui = opt_with_sokol_imgui,
+        .sokol_imgui_cprefix = opt_sokol_imgui_cprefix,
+        .cimgui_header_path = opt_cimgui_header_path,
+        .imgui_version = imguiver_path,
         .emsdk = emsdk,
+        .use_ubsan = sanitize_c,
+        .use_tsan = sanitize_thread,
     });
+
+    var artifact: ?*std.Build.Step.Compile = null;
```
Comment (kassane) [inline build.zig:271]: Currently, ldcBuilStep get a library recursive.
If you split the libs, then the optional imgui condition will need to be refactored.

File: README.md [hunk 3]
```diff
@@ -66,11 +66,21 @@ zig build --help
...
+#                                    docking
+#   -Dubsan=[bool]               Enable undefined behavior sanitizer
+#   -Dtsan=[bool]                Enable thread sanitizer
 #   -Dartifact=[bool]            Build artifacts (default: false)
 #   -DbetterC=[bool]             Omit generating some runtime information and helper functions (default: false)
 #   -DzigCC=[bool]               Use zig cc as compiler and linker (default: false)
+#   -Dshaders=[bool]             Build shaders (default: false)
 #   -Dtarget=[string]            The CPU architecture, OS, and ABI to build for
 #   -Dcpu=[string]               Target CPU features to add or subtract
+#   -Dofmt=[string]              Target object format
```
Comment (kassane) [inline README.md:83]: Please, (**ignore**) zig-upstream feature

**Comment by floooh** [comment]
IIRC the way it is supposed to work in the sokol-zig build.zig is that the sokol C library depends on the Emscripten setup step, and then all other C libraries depend on the sokol library.

E.g. the `lib` here is the sokol C library:

https://github.com/floooh/sokol-zig/blob/935ad0e05eeb6c223d06dcdd16a155c6be8ff49d/build.zig#L202-L204

...and the in the sokol-zig-imgui-sample project, the cimgui lib depends on sokol:

https://github.com/floooh/sokol-zig-imgui-sample/blob/4e09e59c95e04399a04d9e2f39aeb03057813aec/build.zig#L75

...so basically, Emscripten setup finishes first, then the sokol C library is compiled, and then all other C libraries.

**Comment by floooh** [comment]
Oh... the errors here (assert.h not found):

https://github.com/kassane/sokol-d/actions/runs/13225929376/job/36916768510

...look entirely different then the CI error in this PR (those are all linker errors):

https://github.com/kassane/sokol-d/actions/runs/13265008351/job/37030179876

**Comment by kassane** [comment]
> Oh... the errors here (assert.h not found):
> 
> https://github.com/kassane/sokol-d/actions/runs/13225929376/job/36916768510
> 
> ...look entirely different then the CI error in this PR (those are all linker errors):
> 
> https://github.com/kassane/sokol-d/actions/runs/13265008351/job/37030179876

Exactly! ldc2 replace libsokol to libimgui config. :face_exhaling:

**Comment by kassane** [comment]
Evaluating the current construction process involving **imgui**:

- build libsokol
- build libimgui + cimgui (if enabled)
- build D example(s) - get libsokol and libimgui + cimgui.h (dcimgui.d)*


* ldc2/ldmd2 requires reading the header to autogenerate imgui-bindings. Unlike libsokol which has bindings generated in the sokol-upstream. Also ldc2/ldmd2 get all includes + flags/defines from libsokol!

**Comment by kassane** [comment]
Ok. I need help (MacOS user)!!

File: build.zig [hunk 4]
```diff
@@ -676,10 +716,21 @@ pub fn ldcBuildStep(b: *Build, options: DCompileStep) !*std.Build.Step.InstallDi
         b.step("test", "Run all tests");
 
     if (options.target.result.isWasm()) {
+        ldc_exec.step.dependOn(&options.artifact.?.step);
```
Comment (kassane) [inline build.zig:719]: Force libsokol + emsetup load.

File: build.zig [hunk 5]
```diff
@@ -243,11 +260,32 @@ pub fn build(b: *Build) !void {
...
+    var lib_imgui: ?*CompileStep = null;
+    if (opt_with_sokol_imgui) {
+        const imgui = try buildImgui(b, .{
+            .target = target,
+            .optimize = optimize,
+            .version = imguiver_path,
+            .use_ubsan = sanitize_c,
+            .use_tsan = sanitize_thread,
+        });
+        imgui.step.dependOn(&lib_sokol.step);
```
[the remark this answers is not in the document]
Comment (floooh) [reply build.zig:280]: I would keep that an dlet the lib_sokol step depend on the emsdk setup step. E.g. the rule in sokol-zig is that all C libraries should depend on lib_sokol so that all C code only starts to compile after the Emscripten SDK setup has finished.

[the remark this answers is not in the document]
Comment (kassane) [reply build.zig:280]: ok. make sense!

**Comment by kassane** [comment]
Finally https://github.com/kassane/sokol-d/pull/54/commits/96a06dbfeceac39a624f6811b68aa4466c2e62c8 :heavy_check_mark:
